version: '3'

services:
  postgres:
    image: postgres:11
    restart: "no"
    ports:
    - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
